Daedalean coding standards for includes
daedaleanai/llvm-project pull request #11
Opened 2022-03-24 10:33 UTC by finomen

- Only header files may be included
- Each file MUST include all necessary headers for used symbols.
- Include path MUST be relative to workspace root
- Include groups separate by empty line MUST be used in following order:
 1. Related header
 2. Other headers from same directory
 3. Other headers from same project
 4. Library headers
-Includes in one group MUST be ordered lexicographically.

Relates: T10100

2022-03-25 15:07 UTC, aburgm requested changes

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +  const std::string ext = fileName.substr(fileName.find_last_of('.'));
Should first get the basename of the path, otherwise you would process the extension of "a/b.c/d"  as "c.d"

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +    const std::string includeBasename = fileName.substr(fileName.find_last_of('/')).substr(1);
What if filename does not contain "/"?

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +    std::string curBasename = curFileName.substr(curFileName.find_last_of('/')).substr(1);
What if curFileName does not contain a "/"?

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +    const std::string curExt = curFileName.substr(curFileName.find_last_of('.'));
same concern as above. It might make sense to define some utility functions to extract extension and first/last component of the path.

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +  } else if (currentDir.substr(0, prefixSize) == includeDir.substr(0, prefixSize))  {
this would incorrectly return true if currentDir is "exp", prefixSize is 3 and includeDir is "exp-stdlib". Might be good to add a test for it.

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +                         "> should be in different groups");
say "include groups"

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/test/clang-tidy/checkers/Inputs/DDLNHeaders/project1/dir1/tmp.cc.msg
> +clang-tidy applied 1 of 1 suggested fixes.
is this file intended to be checked in?

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/test/clang-tidy/checkers/Inputs/DDLNHeaders/tmp.cc
> +#include <project2/header3.hh>
why does this not have any expected checks about different groups?

2022-03-25 15:07 UTC, aburgm commented on clang-tools-extra/test/clang-tidy/checkers/Inputs/DDLNHeaders/project1/dir1/tmp.cc
> +// C1HECK-MESSAGES: :[[@LINE-8]]:10: warning: <project1/dir1/cls1.hh> and <project1/dir1/header1.hh> should be in different groups [daedalean-include-order]
C1HECK? (How) does this actually work?

Shouldn't there alsobe other messages expected about dir1 and dir2 headers in different groups, and project1/project2?

2022-03-28 11:22 UTC, finomen commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +  const std::string ext = fileName.substr(fileName.find_last_of('.'));
If file has suffix ".hpp" it will get correct extensions, if not - error will be reported, as expected.

2022-03-28 11:35 UTC, finomen commented
About tests I've created T10244. This check is not checkable with llvm test tools

2022-03-28 12:19 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +    std::string curBasename = basename(curFileName);
const?

2022-03-28 12:19 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +  const std::string ext = fileName.substr(fileName.find_last_of('.'));
but it looks like more by accident than by design. You have a thing called `ext` that's not necessarily an extension.

2022-03-28 12:19 UTC, aburgm commented on clang-tools-extra/clang-tidy/daedalean/IncludeOrderCheck.cpp
> +    return {};
I'd argue that it should return `path` in this case; the basename of "bla.c" is "bla.c"

2022-03-28 12:47 UTC, aburgm approved these changes

2022-03-28 13:02 UTC, merged